### ISSUE TITLE
macOS Monterey compatibility?

### ISSUE THREAD

**Issue by ottob** [MacSourcePorts/MSPBuildSystem#2]
I noticed that the latest vkQuake build only supports macOS 13 or later. Is this intentional? Im running 12.6.2 (latest Monterey), keeping support for this would be nice if it's not too much trouble.

**Comment by tomkidd** [comment]
Nope, not intentional. I'm hoping to use this week to get some work done on stuff so I'll add that to the list. 

You have to specify a minimum macOS version or else the build defaults to whatever you build it on and the method of putting this in there is different for different build systems so I'll need to figure out how to pass that in for the thing vkQuake is doing.

Thanks for the heads up.

**Comment by ottob** [comment]
The new build works great. Thanks.
